### ISSUE TITLE
Swapping accelerometer and gyroscope data?

### ISSUE THREAD

**Issue by rmndrs89** [mad-lab-fau/gaitmap#53]
Dear all, 

it is a bit confusing how accelerometer and gyroscope data are used in the Madgwick AHRS implementation. When the data are enumerated over, [the naming of acc and gyro seems to be swapped](https://github.com/mad-lab-fau/gaitmap/blob/4110ecd9dbad04fbd1e4656ec8ba046a5a26ddfb/gaitmap/trajectory_reconstruction/orientation_methods/_madgwick.py#L207). Eventually, two and three lines below this is compensated for by calling: 
```python
            gyro=acc_val,
            acc=gyro_val,
```

but would it not make more sense to just change the zip order, e.g., `for i, (acc_val, gyro_val) in enumerate(zip(acc, gyro)):` and have:
```python
            gyro=gyro_val,
            acc=acc_val,
```

Best regards,
Robbin

**Comment by AKuederle** [comment]
You are completely right. Not sure how this happened. I will fix that later today. Thanks for reporting.
