### ISSUE TITLE
gravity reading on vertical axis

### ISSUE THREAD

**Issue by rakeshpilkar82** [mad-lab-fau/gaitmap#68]
The documentation states the following regarding the coordinate system. 

1. Accelerometer measures a positive value, if movement occurs in the positive (+) direction of the axis
2. Gyroscope measures a positive value, if rotation occurs in the direction of the arrow 
3. Gravity results in a measure of +1g, if an axis is pointing upwards, and -1g, if the axis is pointing downwards

With this reference system, If the sensor is placed on a table (with gravity as only force in play), wouldn't 1 and 3 be the conflicting statements? Shouldn't gravity result in +1g if the arrow is pointing downwards?

**Comment by AKuederle** [comment]
Maybe the wording is not the most accurate here, but what the accelerometer measures while lying on the table is the force the table acts upon the sensor in the direction opposite to gravity. This is basically the typical frame of reference discussion, but think about it this way: When the sensor is in free-fall, it measures 0 acceleration in the inertial frame. So from the perspective of the sensor, it is the floor accelerating towards the sensor, while it is standing still. This means, if the sensor makes contact with the floor, it is being pushed upwards in its frame of reference. Hence, it measures +1g not -1g.

Hope that makes sense :)
