### ISSUE TITLE
Stride segmentation algorithms without using gaitmap_mad

### ISSUE THREAD

**Issue by rakeshpilkar82** [mad-lab-fau/gaitmap#69]
As I understand, all of the stride segmentation algorithms are a part of `gaitmap_mad`. Are there any options for stride segmentation if one wants to use only `gaitmap` and not `gaitmap_mad`?

**Comment by AKuederle** [comment]
Hi, as all of our stride segmentation algorithms were developed in collaboration with our cooperate partners, they are only available under an AGPL3 licence. Check if the licence is actually prohibitive for your usecase. If yes, let us know, and we can talk with our cooperate partners about possible exemption or the potential for a proprietary licence that allows your usecase.

If it is legally not possible for you to use it, I would suggest you validate that things work as expected with the segmentation algorithms in gaitmap-mad and then reimplement an algorithm from literature to replace ours in the chain.

**Comment by AKuederle** [comment]
I will close this, but feel free to reopen, if you need further input on this topic
